### PR TITLE
Set a title rather than using the URL default

### PR DESCRIPTION
**Pull request by GregWeil**
By default the window title is just the url directly, which looks ugly. This is a small change, but I wanted to get a pull request in to make sure I had everything set up properly.

### CODE REVIEW

**Comment by rrdelaney** [comment]
This would be better if it was context aware. Rather than just "SuperFeed", if the location was home the title could be something like "SuperFeed - Home".

**Comment by GregWeil** [comment]
I agree. Looking around it doesn't seem like that can be done with plain react. Do you know if there is a better way to do this than manually setting it?

**Comment by rrdelaney** [comment]
https://github.com/nfl/react-helmet looks like a good solution to this

**Comment by rrdelaney** [comment]
There's an easy way to do this using higher-order components:

``` jsx
const setTitle = title => Component => class extends React.Component {
  componentDidMount () { document.title = title }
  render () { return <Component {...this.props} /> }
}

@setTitle('SuperFeed - Home')
class Home extends React.Component {
  // ...
}
```

**Comment by GregWeil** [comment]
I saw a suggestion like that, but from what I understood that required us to have one on every page. If one of those got added then removed, the title would stay the same rather than reverting to the default.

**Comment by GregWeil** [comment]
Also, I realized I made this from the master rather than a branch, should I close this and recreate it on a branch?

**Comment by rrdelaney** [comment]
PR's to master is fine

**Comment by GregWeil** [comment]
No, PR from master, I think when I commit to GregWeil/SuperFeed from now on it will show up at the bottom of this PR

**Comment by rrdelaney** [comment]
Master -> master PR is fine

**Comment by rrdelaney** [comment]
I implemented this with react-helmet in 3f78ab85763667c1524d4a3829ba82eb54fa0988

**Comment by rrdelaney** [comment]
@GregWeil make sure you ping me when you want a PR to be looked at again

**Pull request closed without merging**
